# Generated by Django 4.1.4 on 2023-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='newpost',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='main.ip'),
        ),
    ]
