# Generated by Django 4.1.4 on 2023-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ip_remove_newpost_likes_newpost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='views',
        ),
        migrations.AddField(
            model_name='newpost',
            name='show_count',
            field=models.IntegerField(default=0),
        ),
    ]
